In [1]:
import pandas as pd

In [2]:
#import panda_datareader as web

In [3]:
!type "C:\\Users\\Yyx_2\\Desktop\\code\\example.txt"

系统找不到指定的文件。

In [4]:
pd.read_csv("C:\\Users\\Yyx_2\\Desktop\\code\\example.txt")

FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Yyx_2\\Desktop\\code\\example.txt'

In [ ]:
pd.read_table("C:\\Users\\Yyx_2\\Desktop\\code\\example.txt",sep=',')

In [5]:
pd.read_csv("C:\\Users\\Yyx_2\\Desktop\\code\\example1.txt",names=[1,2,3,4,'message'],index_col='message')

         1   2   3   4
message
hello    1   2   3   4
world    5   6   7   8
foo      9  10  11  12

In [6]:
fi=pd.read_csv("C:\\Users\\Yyx_2\\Desktop\\code\\example2.txt",index_col=['key1','key2'])
fi

           value1  value2
key1 key2
one  a          1       2
     b          2       3
     c          3       4
     d          4       5
two  a          6       7
     b          8       9
     c         10      11
     d          8       0

In [7]:
pd.read_csv("C:\\Users\\Yyx_2\\Desktop\\code\\example3.txt",sep='\s+')

           A              B     C
aaa     1234           2222  4567
bbb       34            123    12
cccc  234567  2345678901234   333

In [8]:
result=pd.read_csv("C:\\Users\\Yyx_2\\Desktop\\code\\example4.txt",skiprows=[0,2,3],na_values=[1,2])
result

      a    b    c    d message
0   NaN  NaN  3.0  4.0       a
1   NaN  3.0  4.0  5.0     NaN
2   3.0  4.0  NaN  6.0       c
3   4.0  5.0  6.0  7.0       d
4   NaN  NaN  3.0  4.0       a
5   NaN  3.0  4.0  5.0     NaN
6   3.0  4.0  NaN  6.0       c
7   4.0  5.0  6.0  7.0       d
8   NaN  NaN  3.0  4.0       a
9   NaN  3.0  4.0  5.0     NaN
10  3.0  4.0  NaN  6.0       c
11  4.0  5.0  6.0  7.0       d
12  NaN  NaN  NaN  NaN       D
13  NaN  NaN  NaN  NaN       E

In [9]:
pd.isnull(result)

        a      b      c      d  message
0    True   True  False  False    False
1    True  False  False  False     True
2   False  False   True  False    False
3   False  False  False  False    False
4    True   True  False  False    False
5    True  False  False  False     True
6   False  False   True  False    False
7   False  False  False  False    False
8    True   True  False  False    False
9    True  False  False  False     True
10  False  False   True  False    False
11  False  False  False  False    False
12   True   True   True   True    False
13   True   True   True   True    False

In [9]:
k=pd.read_table("C:\\Users\\Yyx_2\\Desktop\\code\\example4.txt",sep=',',skiprows=[0,2,3],nrows=5)

In [10]:
k.to_csv(sys.stdout,sep='|')

NameError: name 'k' is not defined

In [11]:
import csv
with open("C:\\Users\\Yyx_2\\Desktop\\code\\example4.txt") as f:
    lines=list(csv.reader(f))

In [12]:
header,values=lines[0],lines[1:]

In [13]:
dickion={h:v for h,v in zip(header,zip(*values))}

In [14]:
dickion

{'#qwqwqww': ('a',
  '#just for fun',
  '#never mind',
  '1',
  '2',
  '3',
  '4',
  '1',
  '2',
  '3',
  '4',
  '1',
  '2',
  '3',
  '4',
  '1',
  '2')}

In [15]:
tables=pd.read_html("C:\\Users\\Yyx_2\\Desktop\\code\\sale_test.html")

In [16]:
len(tables)

1

In [17]:
tables

[      订单ID 客户姓名  产品类别     产品名称        销售日期  数量   单价(元)  销售额(元)  地区
 0   ORD001   张三  电子产品     智能手机  2024-01-15   1  2999.0  2999.0  华东
 1   ORD002   李四    家电      洗衣机  2024-01-20   1  1899.0  1899.0  华北
 2   ORD003   王五    服装     冬季外套  2024-01-25   2   599.0  1198.0  东北
 3   ORD004   赵六  电子产品    笔记本电脑  2024-02-05   1  6599.0  6599.0  华东
 4   ORD005   钱七    食品  进口巧克力礼盒  2024-02-14   5   199.0   995.0  华南
 5   ORD006   孙八    家电      电冰箱  2024-02-20   1  3299.0  3299.0  华中
 6   ORD007   周九  电子产品     无线耳机  2024-03-01   3   399.0  1197.0  华东
 7   ORD008   吴十    服装      运动鞋  2024-03-08   2   499.0   998.0  西南
 8   ORD009  郑十一    食品     有机茶叶  2024-03-15   4   299.0  1196.0  华北
 9   ORD010  王十二  电子产品     平板电脑  2024-03-20   1  4299.0  4299.0  华东
 10  ORD011  李十三    家电       空调  2024-03-25   2  2599.0  5198.0  华南
 11  ORD012  张十四    食品     高档红酒  2024-03-30   1   899.0   899.0  华东]

In [18]:
from lxml import objectify
path="C:\\Users\\Yyx_2\\Desktop\\code\\company_data.xml"
with open(path, 'r', encoding='utf-8') as f:
     parsed = objectify.parse(f)
     root = parsed.getroot()

In [19]:
data=[]
skip_fields=[]
for elt in root.employees.employee:
    el_data={}
    for child in elt.getchildren():
        if child.tag in skip_fields:
            continue
        el_data[child.tag]=child.text
    data.append(el_data)
pd.DataFrame(data)

,name,age,gender,position,department,salary,hire_date,email,skills
0,陈小伟,32,男,高级算法工程师,dept001,35000,2019-03-15,chenxiaowei@yuanbao.com,None
1,刘静,28,女,销售经理,dept002,28000,2020-07-10,liujing@yuanbao.com,None
2,赵天宇,26,男,前端开发工程师,dept001,22000,2021-09-05,zhaotianyu@yuanbao.com,None
3,孙雨薇,30,女,客户支持专家,dept003,18000,2018-11-20,sunyuwei@yuanbao.com,None
4,周浩然,29,男,UI/UX设计师,dept001,25000,2020-04-12,zhouhaoran@yuanbao.com,None

In [20]:
pd.read_csv("C:\\Users\\Yyx_2\\Desktop\\code\\example.csv")

   a   b   c   d message
0  1   2   3   4   hello
1  5   6   7   8   world
2  9  10  11  12    reap

In [45]:
fi=pd.read_excel("C:\\Users\\Yyx_2\\Desktop\\code\\try.xlsx")
lines0=[]
for i in range(3):
    lines0.extend(fi.loc[i])
lines0

[np.int64(1),
 np.int64(1),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 'hello',
 np.int64(2),
 np.int64(2),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 'world',
 np.int64(3),
 np.int64(3),
 np.int64(4),
 np.int64(5),
 np.int64(6),
 'reap']

In [47]:
tot=0
for i in [0,1,2,3,4,6,7,8,9,10,12,13,14,15,16]:
    tot+=lines0[i]
print(tot)

48

In [38]:
import requests

In [39]:
url='https://api.github.com/repos/pandas-dev/pandaa/issues'

In [40]:
resp=requests.get(url)
resp

In [41]:
data=resp.json()
data[0]['title']

KeyError: 0